on:
  pull_request: ~
  push:
    branches:
      - "main"
      - "[0-9].*"

name: Static analysis

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-
          
      - name: Download dependencies
        run: |
          composer update --no-interaction --no-progress --optimize-autoloader
          composer bin phpstan install --no-interaction --no-progress --optimize-autoloader
          
      - name: Run PHPStan
        run: |
          vendor/bin/phpstan --no-progress